# Generated by Django 6.0.5 on 2026-05-28 08:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id_enseignant', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'db_table': 'enseignants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('numero_etudiant', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='N° étudiant')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('groupe', models.CharField(max_length=20, verbose_name='Groupe')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_etudiants/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'db_table': 'etudiants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('code_ressource', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code ressource')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('descriptif', models.TextField(blank=True, verbose_name='Descriptif')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Coefficient')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'db_table': 'ressources',
                'ordering': ['ue', 'code_ressource'],
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('code_ue', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code UE')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'UE")),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6')], max_length=2, verbose_name='Semestre')),
                ('credits_ects', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Crédits ECTS')),
            ],
            options={
                'verbose_name': 'UE',
                'verbose_name_plural': 'UE',
                'db_table': 'ue',
                'ordering': ['semestre', 'code_ue'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('date', models.DateField(verbose_name='Date')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Coefficient')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='notes_app.ressource', verbose_name='Ressource associée')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'db_table': 'examens',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='ressource',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='notes_app.ue', verbose_name='UE associée'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note /20')),
                ('appreciation', models.CharField(blank=True, max_length=255, verbose_name='Appréciation')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes_app.etudiant', verbose_name='Étudiant')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes_app.examen', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'notes',
                'unique_together': {('etudiant', 'examen')},
            },
        ),
    ]
